services:
  - type: web
    name: crackscan
    env: python
    buildCommand: pip install -r requirements.txt && python download_model.py
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0